export const GL_STATE_UPDATE = "GL_STATE_UPDATE";
export const GL_UI_UPDATE = "GL_UI_UPDATE";
export const GL_PAUSE_RENDER = "GL_PAUSE_RENDER";
export const GL_RESUME_RENDER = "GL_RESUME_RENDER";
export const GL_INIT_EXPERIENCE = "GL_INIT_EXPERIENCE";

export const GL_EARLY_UPDATE_TOPIC = "GL_EARLY_UPDATE_TOPIC";
export const GL_UPDATE_TOPIC = "GL_UPDATE_TOPIC";
export const GL_LATE_UPDATE_TOPIC = "GL_LATE_UPDATE_TOPIC";

// gl publish
export const GL_READY = "GL_READY";
